# -*- coding: utf-8 -*-

# MainWindow implementation generated from reading ui file 'network-ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal, pyqtSlot, QObject
import socket, time, threading

#TODO Change self.port into self.Port
#TODO thread.finished NOT WORKING !!!!!


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 181)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.IPLabel = QtWidgets.QLabel(self.centralwidget)
        self.IPLabel.setObjectName("IPLabel")
        self.gridLayout.addWidget(self.IPLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 6, 1, 1)
        self.ConnectButton = QtWidgets.QPushButton(self.centralwidget, enabled=False)
        self.ConnectButton.setObjectName("ConnectButton")
        self.gridLayout.addWidget(self.ConnectButton, 6, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 5, 6, 1, 1)
        self.StatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.StatusLabel.setObjectName("StatusLabel")
        self.gridLayout.addWidget(self.StatusLabel, 3, 6, 1, 1)
        self.PortLabel = QtWidgets.QLabel(self.centralwidget)
        self.PortLabel.setObjectName("PortLabel")
        self.gridLayout.addWidget(self.PortLabel, 0, 7, 1, 1)
        self.IPInput = QtWidgets.QLineEdit(self.centralwidget)
        self.IPInput.setObjectName("IPInput")
        self.gridLayout.addWidget(self.IPInput, 0, 1, 1, 1)
        self.PortInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PortInput.setObjectName("PortInput")
        self.gridLayout.addWidget(self.PortInput, 0, 8, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Client"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.PortLabel.setText(_translate("MainWindow", "PORT :"))
        self.IPLabel.setText(_translate("MainWindow", "IP :"))
        self.StatusLabel.setText(_translate("MainWindow", ""))

    def InitSignals(self):
        self.IPInput.textChanged.connect(self.enableConnectButton)
        self.PortInput.textChanged.connect(self.enableConnectButton)
        self.ConnectButton.clicked.connect(self.connectServer)

    def enableConnectButton(self):
        try:
            if len(self.IPInput.text()) > 0 and len(self.PortInput.text()) > 0:
                if int(self.PortInput.text()) < 65535 and int(self.PortInput.text()) > 0:
                    self.ConnectButton.setEnabled(True)
                    self.Ip = self.IPInput.text()
                    self.port = self.PortInput.text()

                else:
                    self.ConnectButton.setDisabled(True)
                    self.StatusLabel.setText(
                        "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#F00000;\">Port number must be lower than 65535!</span></p></body></html>")

            else:
                self.ConnectButton.setDisabled(True)

        except ValueError:
            self.StatusLabel.setText(
                "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#F00000;\">Error in Port Number !</span></p></body></html>")

    def connectServer(self):
        self.ConnectButton.setDisabled(True)
        self.obj = Server(self.Ip, self.port)
        self.thread = QtCore.QThread()
        self.obj.StatusReport.connect(self.updateStatus)
        self.obj.moveToThread(self.thread)
        self.thread.finished.connect(lambda x : print("hey"))
        self.thread.started.connect(self.obj.ConnectServer)
        self.thread.start()


    def disableButtons(self, Button):
        Button.setDisabled(True)


    def enableButtons(self, Button):
        Button.setEnabled(True)

    def updateStatus(self, Color, Text):
        self.StatusLabel.setText(
            "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:{};\">{}</span></p></body></html>".format(
                Color, Text))


class ChatUi(object):

    def setupChatUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.MessageInput = QtWidgets.QTextEdit(MainWindow)
        self.MessageInput.setObjectName("MessageInput")
        self.gridLayout.addWidget(self.MessageInput, 1, 1, 1, 1)
        self.MessageLabell = QtWidgets.QLabel(MainWindow)
        self.MessageLabell.setObjectName("MessageLabell")
        self.gridLayout.addWidget(self.MessageLabell, 1, 0, 1, 1)
        self.SendButton = QtWidgets.QPushButton(MainWindow)
        self.SendButton.setObjectName("SendButton")
        self.gridLayout.addWidget(self.SendButton, 1, 2, 1, 1)
        self.MainChat = QtWidgets.QTextBrowser(MainWindow)
        self.MainChat.setObjectName("MainChat")
        self.gridLayout.addWidget(self.MainChat, 0, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.retranslateChatUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateChatUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chat {}"))
        self.MessageLabell.setText(_translate("MainWindow", "Message :"))
        self.SendButton.setText(_translate("MainWindow", "Send"))

    # def sendData(self):
    #     data = self.lineEdit.text()
    #     if data != "":
    #         self.s.sendData(data)
    #         self.lineEdit.clear()
    #         self.chatText.append("You: " + data)
    #     else:
    #         pass


class Server(QObject):
    StatusReport = pyqtSignal(str, str)
    ChatTextReport = pyqtSignal(str)
    finished = pyqtSignal()
    EnableButton = pyqtSignal(QObject)
    DisableButton = pyqtSignal(QObject)

    def __init__(self, Ip, Port):
        QObject.__init__(self)
        self.Ip = Ip
        self.Port = Port
        self.serverSocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.serverSocket.settimeout(1)
        self.fragments = []

    def ConnectServer(self):
        try:
            self.StatusReport.emit("#1ABC9C", "Connecting...")
            self.serverSocket.connect((self.Ip, int(self.Port)))
            self.StatusReport.emit("#8E44AD", "Connected to {}".format(self.Ip))
            self.DisableButton.emit(ui.ConnectButton)
            self.serverSocket.settimeout(None)
            # self.FetchThread = threading.Thread(target=self.FetchServer)
            # self.FetchThread.start()

        except socket.timeout:
            self.StatusReport.emit("#FF0000", "Connection Timed out !")
            self.EnableButton.emit(ui.ConnectButton)
            self.finished.emit()
            while True:
                pass

        except socket.gaierror:
            self.StatusReport.emit("#FF0000", "Error in IP Address !")
            self.EnableButton.emit(ui.ConnectButton)
            self.finished.emit()
            while True:
                pass
        except ConnectionRefusedError:
            self.StatusReport.emit("#FF0000", "Connection refused by server !")
            self.EnableButton.emit(ui.ConnectButton)
            self.finished.emit()
            while True:
                pass

    def FetchServer(self):

        while True:
            data = self.serverSocket.recv(2048)
            if not data:
                self.StatusReport.emit("#FF0000", "Connexion Lost !")
                self.EnableButton.emit(ui.ConnectButton)
                break
            else:
                data = data.decode("UTF8")
                self.ChatTextReport.emit(data)

    def sendData(self, data):
        self.serverSocket.send(bytes(data, "UTF-8"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.InitSignals()
    MainWindow.show()
    sys.exit(app.exec_())
